[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "PLEIADES"
authors = [{name = "Alexander M. Long", email = "asdkjsd@gmail.com"}]
dynamic = ["version", "description"]